---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: visual_studio_code-ubuntu
    image: ubuntu:16.04
  - name: visual_studio_code-fedora
    image: fedora:27
  - name: visual_studio_code-centos
    image: centos:7

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
