---
# scudcloud client is installed via a repo for either ubuntu or fedora

- name: do these tasks for Ubuntu systems
  block:
    - name: install|deb| add the apt repository
      become: true
      apt_repository:
        repo: ppa:rael-gc/scudcloud
        state: present
    - name: install|deb| accept msttcorefonts eula
      become: true
      debconf:
        name: ttf-mscorefonts-installer
        question: msttcorefonts/accepted-mscorefonts-eula
        value: true
        vtype: select
    - name: install|deb| run the equivalent of "apt-get update"
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 5
  when: ansible_distro == "ubuntu"

- name: install| install scudcloud from repo
  become: true
  package:
    name: scudcloud
    state: present
